### PR TITLE
Paul Lewis added

### PR DESCRIPTION
**Pull request by cyrilf**
Works at Google on the Chrome Developer Relations team as an advocate.

### CODE REVIEW

**Comment by duckspeaker** [comment]
Can you just run the opml generation script to update the opml file? (see contributing.md)

**Comment by cyrilf** [comment]
Yes you're right!
Well, I'm not currently using my computer (I've use the Github interface), so I may do it tommorow :wink: (_or I can send a second PR with the `.opml` file updated._)

**Comment by duckspeaker** [comment]
It's cool; it's quick enough to do myself.

**Comment by cyrilf** [comment]
Alright! Thanks

**Pull request merged**
