### PR TITLE
add new pull request rule

### PR DESCRIPTION
**Pull request by meisyal**
I saw there are some pull requests that contain two or more commits. As a common practice, it's recommend that contributors squash all their commits into one commit for each PR they submit.
I look there are many open source projects mostly using this rule. This is just an idea.

What do you think guys? 

Note: I should create an issue first before I make this pull request. Sorry, I did this hurriedly.

### CODE REVIEW

**Comment by kilimchoi** [comment]
Yea I think it's a good idea for maintaining tidy commit history.

**Comment by duckspeaker** [comment]
Could you provide some examples of well-known open source projects with a hard one commit per PR rule?

**Comment by meisyal** [comment]
@kilimchoi Thank you for merging my pull request.
You're right. I will help you to remind the contributor. I hope everybody else thinks the same way.

Feel free to revert my PR.

@duckspeaker Thanks for asking.
I give you some examples of well-known open source below:
- Rails, check it out [here](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html).
- Discourse, read [here](https://github.com/discourse/discourse/blob/master/CONTRIBUTING.md#contributing-step-by-step).

**Comment by dideler** [comment]
@meisyal There are a few popular open source projects that require patches to be squashed into a single commit, I think for example Android and Eclipse (or any other project that uses Gerrit), but Rails and Discourse do not.

A common practice is to only squash commits when it makes sense (e.g. a typo fix or work-in-progress), instead of always doing it as introduced in this PR.

If you take a closer look at Rails and Discourse, they follow this guideline of squashing when appropriate.

Rails
> Please squash your commits into a single commit when appropriate

Discourse
> Before submitting a pull-request, clean up the history, go over your commits and squash together minor changes and fixes into the corresponding commits.

In practice it's often the case that a PR will (or should) have a single commit as multiple commits can be a signal that there are unrelated changes that are better suited for multiple PRs. But you still occasionally see multiple commits, e.g. [rails/pull/11352](https://github.com/rails/rails/pull/11352/commits) and [discourse/pull/3638](https://github.com/discourse/discourse/pull/3638/commits).

**Comment by meisyal** [comment]
Good explanation, @dideler.
Sorry, I missed these points.
Thanks for fixing.

**Pull request merged**
