### PR TITLE
Add Snapdeal Engineering Blog

### PR DESCRIPTION
**Pull request by askhubchandani**

### CODE REVIEW

**Comment by kaizensoze** [comment]
This doesn't have enough technical posts, but http://engineering.snapdeal.com/category/code/ does.

**Comment by askhubchandani** [comment]
Done.

**Comment by kaizensoze** [comment]
Did you manually add the feed to the xml file or did it show up. The cert is invalid so it shouldn't be there. If it was automatically added, can you add it to the ignore list in the generate_opml script?

**Comment by askhubchandani** [comment]
I added it manually. I have no idea how to add it automatically. You told me that, "Cert is invalid". What is Cert? What am I exactly supposed to do now? I am a beginner here.

**Comment by askhubchandani** [comment]
In a collection of Engineering Blogs what is exactly the need of XML URL?

**Comment by kaizensoze** [comment]
The security cert of the website is invalid. The xml is for an rss feed to import into an rss reader. I can go ahead and remove it from the xml file.

**Comment by kaizensoze** [comment]
Merged: b5bba8ea605f1d523af5de863df4bda18cd26f65

**Pull request closed without merging**
