### PR TITLE
Add SmartRecruiters engineering blog

### PR DESCRIPTION
**Pull request by ArturSkowronski**

### CODE REVIEW

**Comment by kilimchoi** [comment]
Please write a brief description of why I should add it.

**Comment by ArturSkowronski** [comment]
We just started recently, but we are strictly Engineering division of the company called SmartRecruiters. We are not recruiters, but we create Recruitment software.

We don't plan any content marketing, just purely engineering stuff. 

It would be great to have an opportunity to be on your list.

**Comment by kilimchoi** [comment]
I think there need to be more content. Please open PR again sometime in the future when you guys have more than 20 posts.

**Comment by ArturSkowronski** [comment]
Of course, I will do that! Thanks for Feedback

**Pull request closed without merging**
