### PR TITLE
 added link to wired science

### PR DESCRIPTION
**Pull request by luanribeiros**
Blog dedicated to the science of Wired, magazine reference when it comes to new technologies, internet, behavior and practically everything that is interesting and new in the world. In Wired Science, subjects ranging from space exploration to electronic implants in humans are discussed.

### CODE REVIEW

**Comment by luanribeiros** [comment]
Gizmodo - One of the biggest technology blogs in the world. Want to know what the revolutionary new product from Apple? Gizmodo will give you all the information possible before everyone else. For the engineer who needs to be always up to date on products and technology trends, Gizmodo is essential.

**Comment by kaizensoze** [comment]
Can you break it up into one add per pull request?

**Comment by wcerfgba** [comment]
@luanribeiros Thanks for your contribution but I do not think it is suitable because this repo is for collecting blogs primarily associated with software engineering. Suggest we close this PR.

**Comment by kaizensoze** [comment]
Agreed, closing.

**Pull request closed without merging**
