### PR TITLE
Add Checkr

### PR DESCRIPTION
**Pull request by jperichon**

### CODE REVIEW

**Comment by kilimchoi** [comment]
There need to be more technical posts. Please re-open it later.

**Comment by jperichon** [comment]
@kilimchoi thanks for the quick review -- do you have any number of posts in mind?
eg: https://up.smartrecruiters.com/ and https://medium.com/@kirill_shevch/latest were accepted with less or equal amount of technical posts.
Thanks

**Comment by kilimchoi** [comment]
We try to be as selective as possible when it comes to company blogs because we've seen so many blogs filled with marketing spam. I try to gauge the quality of the blog before I merge anything in and smartrecruiters might have been merged in by @kaizensoze. I don't recall adding it in. It looks like they don't have much either. I will have to remove them. Please aim for more than 10 technical posts. We don't want to be adding just any companies anymore since it's sorta becoming a long list of company blogs in the planet.

**Comment by kilimchoi** [comment]
There's also guideline we published. Please read it before making a pr https://github.com/kilimchoi/engineering-blogs/blob/master/contributing.md

**Comment by kaizensoze** [comment]
What can I say? I'm more lenient. I don't really agree with the minimum posts requirement. If I created a high quality blog with 1 or 2 posts to start, I'd want it added to the list asap. Of course it'd be annoying if it's added and the blog sees no further activity but a dead blog is a dead blog whether it's 2 or 10 posts and there currently isn't a process that goes through and checks for dead blogs other than what I do about once a month or so, which is delete the opml locally, run the generation script and see which blogs are no longer around.

**Comment by jperichon** [comment]
No problem, will re-open when we have more posts! Thanks

**Pull request closed without merging**
