### PR TITLE
Add @elbrujohalcon's medium

### PR DESCRIPTION
**Pull request by elbrujohalcon**

### CODE REVIEW

**Comment by kaizensoze** [comment]
Can you just update the rss so it's in sync with the blog?

**Comment by elbrujohalcon** [comment]
Isn't that already done?

**Comment by elbrujohalcon** [comment]
oh, https!! I see

**Comment by elbrujohalcon** [comment]
fixed :)

**Comment by kaizensoze** [comment]
I meant there's a mismatch of posts (including ordering) between the blog and rss feed.

**Comment by elbrujohalcon** [comment]
Oh, that's entirely up to Medium. I have no idea how to fix that.

**Comment by kaizensoze** [comment]
Ah ok.

**Pull request merged**
