### PR TITLE
Updated with my blog

### PR DESCRIPTION
**Pull request by prashantpandeyfun10**

### CODE REVIEW

**Comment by prashantpandeyfun10** [comment]
Hi..I have submitted my blog. Hope you get it. Sorry for the trouble

**Comment by kilimchoi** [comment]
Did you read contributing.md? First, your blog should go under individuals section. Second, you should run opml generator to get rss feed url.

**Comment by kilimchoi** [comment]
Also, I feel that your blog doesn't have too many interesting posts yet to appeal to a lot of people. Sorry, but I might have to close this PR.

Best,
Kilim

**Comment by prashantpandeyfun10** [comment]
Cool! Np.

**Pull request closed without merging**
