### PR TITLE
Added Crowdfire's Engineering Blog

### PR DESCRIPTION
**Pull request by siddharthgopi**

### CODE REVIEW

**Comment by kaizensoze** [comment]
Just remove the file permission changes on Gemfile, Gemfile.lock, and contributing and should be good to go.

**Comment by siddharthgopi** [comment]
Ah, i was wondering why all files got modified. Changing now :)

**Comment by siddharthgopi** [comment]
gemfile 644
gemfile.lock 644
contributing 644

**Comment by siddharthgopi** [comment]
Done.

**Comment by kaizensoze** [comment]
Thanks.

**Pull request merged**
