### PR TITLE
Add godaddy engineering blog

### PR DESCRIPTION
**Pull request by nikoo28**

### CODE REVIEW

**Comment by mesolimbo** [comment]
GoDaddy is a super shady company, please don't add them: https://www.geek.com/news/godaddy-ceo-bob-parsons-boasts-killing-an-elephant-leopard-on-vacation-video-1335435/

**Comment by jacktuck** [comment]
@mesolimbo he isn't ceo anymore but agree they have a questionable past. Their eng blog looks decent, though.

**Comment by nikoo28** [comment]
@mesolimbo, the link you posted it way too old. We got some nice projects that we have been working on recently.

**Comment by mesolimbo** [comment]
Think about it this way: If, as a company, Godaddy never did anything to make amends, then all their engineering work is built on top of that same blood money. There's some nice engineering at Monsanto and Philip Morris, but we don't have to celebrate it and promote it if the net effect on civilization is negative.

**Comment by sushantmimani** [comment]
@mesolimbo  I don't see you protesting the inclusion of Riot Games in the list and their negative effect on civilization is quite _recent_. Just saying.

**Comment by mesolimbo** [comment]
That one got past my radar I guess ... and human-on-human crimes are a whole other story. Elephants are a lot scarcer and helpless.

**Comment by kilimchoi** [comment]
Sorry we are not adding any more new blogs

**Pull request closed without merging**
