### PR TITLE
Revert "Add Ticketmaster's engineering/tech blog."

### PR DESCRIPTION
**Pull request by Githubcatadmin**
Reverts kilimchoi/engineering-blogs#163

### CODE REVIEW

**Comment by kilimchoi** [comment]
Why are you reverting it?

**Comment by Githubcatadmin** [comment]
I don't think it's a good idea adding more stuff,and besides you already have enough crap!

**Comment by riichard** [comment]
I agree with the cat we are making this list pretty long and maybe loose
too much quality by getting too many pr-like blogs. (Not saying that
ticketmaster is off topic).

But you've been commenting on nearly all submissions today. I think you're
too aggressive and talking too much off topic. If you don't agree with the
blogs, start an issue with a proposal for quality control.

**Comment by Githubcatadmin** [comment]
Don't call me cat!!!!!!!!!!!I'm a GitHub admin!!!!!the cat is their symbol!!!

**Pull request closed without merging**
