### PR TITLE
OPML for RSS Readers

### PR DESCRIPTION
**Pull request by tkhemani**

### CODE REVIEW

**Comment by rakanalh** [comment]
How will this be up to date with all the changes that take place on this repo?

**Comment by tkhemani** [comment]
Not Sure if there's a way to automate this. I used this: reader.feedshow.com/goodies/opml/OPMLBuilder-create-opml-from-rss-list.php

**Comment by kilimchoi** [comment]
These links are not entirely accurate as Buzzfeed, Canva, Boxever, Datafox, Megeeks don't have a rss feed. Try the link yourself. And they're just a few I discovered. There might be more.

**Comment by duckspeaker** [comment]
That seems pretty tedious. I think the easiest way would be to write a script that takes the name/url pairings from the markdown, get the corresponding rss urls for the web urls that have one, and generate the opml.

You could use something like this for checking if there's an rss url: 
http://ajax.googleapis.com/ajax/services/feed/lookup?v=1.0&q=http://martinfowler.com/

and to generate the opml:
http://stackoverflow.com/questions/1244255/write-to-xml-in-ruby

(I looked into generating xml with python and it seems messy in comparison:
http://stackoverflow.com/questions/3605680/creating-a-simple-xml-file-using-python)

**Comment by duckspeaker** [comment]
I added a script that generates opml from the readme along with the generated opml.

**Pull request closed without merging**
