### PR TITLE
Added Nikola Brežnjak's blog

### PR DESCRIPTION
**Pull request by Hitman666**

### CODE REVIEW

**Comment by duckspeaker** [comment]
Alright so three things wrong with this:

1) Not an engineering blog.
2) Don't commit the Gemfile change removing "BUNDLED WITH".
3) README entry is in the wrong spot alphabetically.

**Comment by Hitman666** [comment]
I beg to differ. Can you please explain how my blog is not an engineering one? I have posts featured on CodeProject, HackHands and JavascriptWeekly. I mean, no mean to argue or anything, but would appreciate an explanation. Thanks

**Comment by duckspeaker** [comment]
It looks like you added the wrong url. Did you mean to use http://www.nikola-breznjak.com/blog/?

**Comment by Hitman666** [comment]
Ah, you're totally correct :(. I'll fix it now, along with other 2 things, and resubmit the pull request. Thanks for pointing out the error and keeping an open mind about it!

**Comment by duckspeaker** [comment]
Cool, done.

**Comment by Hitman666** [comment]
Great, thanks, have a great weekend!

**Pull request merged**
