### PR TITLE
Add CircleCI

### PR DESCRIPTION
**Pull request by pbiggar**

### CODE REVIEW

**Comment by JoshSmith** [comment]
:+1:

**Comment by kilimchoi** [comment]
Sorry too many PRish posts starting with "Announcing..."

**Comment by pbiggar** [comment]
Almost everything we announce is technical, but I take your point.

I had a look and it's 5/8 tech content on the first page, and about 50% tech content overall. What ratio would work for you?

**Comment by kilimchoi** [comment]
Looking for something that's close to 80% technical.

**Comment by kilimchoi** [comment]
If there's a way to filter the blog posts by engineering content only, I will be happy to add it.

**Pull request closed without merging**
