### PR TITLE
Add Doctolib

### PR DESCRIPTION
**Pull request by pabuisson**

### CODE REVIEW

**Comment by kilimchoi** [comment]
I think you should run opml generator file.

**Comment by pabuisson** [comment]
> I think you should run opml generator file.

I actually did but no feed was detected. However, I notice medium does generate a feed but it contains not only engineering content, but also regular Doctolib company content that might not be interesting to people finding this repo... so I did not add it.

**Comment by kilimchoi** [comment]
Ok then, I think it's best to close this one. Is it possible for you to split it so that we can only receive engineering related posts in the feed?

**Comment by pabuisson** [comment]
I'm looking into this. We might do something, but it will require some work on our side first. I'll keep you posted before the end of the week.

**Pull request closed without merging**
