### PR TITLE
Add blogfoster's engineering blog

### PR DESCRIPTION
**Pull request by meisyal**
As titled.

Needs review.
Thank you.

### CODE REVIEW

**Comment by kaizensoze** [comment]
Thanks. Can you just capitalize blogfoster?

**Comment by meisyal** [comment]
I followed the original name of blogfoster. This company name is non-capitalized.
OK. I will capitalize blogfoster. Should I squash this commit after making changes?

**Comment by kaizensoze** [comment]
Yeah I know but I think the policy has been to capitalize even if the actual name isn't. It's not necessarily something I agree with, but consistency is key.

I can just use the github squash and merge option if you don't want to squash commits yourself.

**Comment by meisyal** [comment]
I just capitalized blogfoster name. The old commit message has been squashed into a new one.

**Comment by kaizensoze** [comment]
Thanks!

**Pull request merged**
