### PR TITLE
Add Compile engineering blog

### PR DESCRIPTION
**Pull request by cyriac**
Adds the Compile Engineering blog. Topics include Python, Django, Data, NLP and Open Source

### CODE REVIEW

**Comment by kilimchoi** [comment]
Please write a brief description of why I should add it.

**Comment by cyriac** [comment]
Missed it. Added now.

Would be a good idea to set up a [PR template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) so that others don't miss it.

**Comment by kilimchoi** [comment]
@cyriac, we have it in contributing.md

**Comment by kilimchoi** [comment]
You guys need more posts. Please open them again when you have more than 20.

**Pull request closed without merging**
