### PR TITLE
Update opml generator

### PR DESCRIPTION
**Pull request by hnq90**
- Add .gitignore
- Wrap blog list outline in parent outline
- Update opml generator
- Remove Gemfile.lock

### CODE REVIEW

**Comment by duckspeaker** [comment]
I feel like this is just nitpicking. Double quotes have been replaced with single quotes. Camel case has been replaced with underscore. A gem has been added not to reduce code but to add it. Also why is Gemfile.lock in gitignore?

**Comment by hnq90** [comment]
@duckspeaker 

> I feel like this is just nitpicking. 

Okay. You don't need to merge my PR.

> Double quotes have been replaced with single quotes. Camel case has been replaced with underscore.

I use Rubocop to check coding style. 

> A gem has been added not to reduce code but to add it.

`feedbag` is included because some blogs' feed couldn't be fetched by Google Feed API. So we need to find it by using `feedbag` or check manually by adding `/rss, /feed, feeds` into the end of web url. So the OPML file is missing ~40 websites.

And after add your original OPML file into Feedly, all the feed would be saved into Uncategorized section. It's quite hard to organize those feeds. So I wrap your old outline tags into a parent outline tag name Engineering Blog. Does it make sense?

> Also why is Gemfile.lock in gitignore?

Keep track history of Gemfile.lock have some issues in different OS.

**Comment by duckspeaker** [comment]
Thanks for the reply. I'm definitely not arguing with RuboCop and I missed the benefit of Feedbag catching more feeds since adding the parent outline showed everything as changed. I tried to remove feedbag and consolidate adding the "helper paths" into the google feed api code but it still didn't find as many (feedbag seems to do an implicit auto-magical subpath search) so leaving it in. Also good call on wrapping everything in an extra outline tag. I had intended that and didn't realize it wasn't, thus messing up the organization of everyone's rss readers.

Do you know of a way to suppress feedbag error output for things like 404 and ssl errors?

**Comment by hnq90** [comment]
@duckspeaker 
I think you could monkey patch this file. It's not recommended but it may be difficult to catch those errors from `feedbag`.
(feedbag.rb)[https://github.com/damog/feedbag/blob/master/lib/feedbag.rb]

Btw, I think you should let people to add feed url by themselves because there are many websites which feed url is couldn't detected automatically.

The format maybe: 
`Name - Web URL - Feed URL`

(I have to erase my Feedly account data after import your OPML :tada:)

**Pull request merged**
