### PR TITLE
Added thetrainline engineering blog and updated opml

### PR DESCRIPTION
**Pull request by griffio**
Added
http://engineering.thetrainline.com/
http://engineering.thetrainline.com/feed/

### CODE REVIEW

**Comment by kilimchoi** [comment]
Are you sure about adding this? I don't see too many interesting articles.

**Comment by griffio** [comment]
I  can re-up the pull request with another one, of course you are the quality control for the list.

What one would you like today, I think these are stronger content?

http://engineering.klout.com/
https://tech.coursera.org/
http://engineering.flipboard.com/
https://blog.srcclr.com/categories/software-development/

I prefer to upload once a-day to avoid spamming,

**Comment by duckspeaker** [comment]
Thetrainline looks kinda eh and coursera only has one entry but feel free to create a new pull request for klout.

**Comment by griffio** [comment]
closed this as per editorial suggestions

**Comment by kilimchoi** [comment]
I am thinking that our list is getting way too long and there are just way too many blogs to serve as signals. Also, it's not always the case that the blog has good articles everytime. So I was thinking that instead of adding a blog link, we should add a link to the new article. I think I can do this on slicedham and create a rss feed for people to get updates. What do you guys think?

**Comment by duckspeaker** [comment]
Not sure I understand. The current use case of loading the opml file into something like digg reader and having the reader set to show unread only essentially does this.

**Comment by kilimchoi** [comment]
I understand that but what I'm trying to say is that I only want to read something truly educational not some tech blog thinly veiled marketing spam. Readers just pull all these content from the blog list we have. What I want to do is something similar to a community site where people submit the best tech blog article.

**Comment by griffio** [comment]
So, to provide in a feed the best slices cut from the tech blogs out there - like hackernews but more focused/curated.

Submissions that would all be done from the slicedham website or still initiated as PR in github?

**Comment by kilimchoi** [comment]
We can do it from slicedham.

**Comment by duckspeaker** [comment]
Yeah that's a very manual thing. You're now curating content on a per blog post basis. Best place to do that would be slicedham via a "Featured" tag (or maybe call it "Prime Cut"). You could also have an upvote system.

**Comment by kilimchoi** [comment]
yes. It would be very manual if I were to moderate every post that will be submitted. However, I think I can give some people posting rights where they can submit without any kind of approvals.

**Comment by griffio** [comment]
I don't know if you have seen https://lobste.rs/, it is an alternative tech link aggregator site?
See https://lobste.rs/about.

To keep slicedham focused, perhaps invite some of the posters from the best engineering blogs, so they can get their content out there.

**Comment by kilimchoi** [comment]
wow never heard of them until now but it pretty looks similar to what I was thinking about.

**Comment by kilimchoi** [comment]
Seems like a really closed community though. I cannot sign up unless I have an invitation. What a bummer :(

**Comment by griffio** [comment]
Yes, the moderation log shows that the site owner is quite hands-on in purging content and users.
https://lobste.rs/moderations.  

The site is open source: https://github.com/jcs/lobsters.

**Pull request closed without merging**
