### PR TITLE
Added SteelSeries Techblog

### PR DESCRIPTION
**Pull request by mike-u**
SteelSeries Techblog http://techblog.steelseries.com/

### CODE REVIEW

**Comment by kilimchoi** [comment]
Steelseries has too many promotional posts about their engine.

**Comment by mike-u** [comment]
Fair enough. I thought the GoLisp entries were interesting though.

**Comment by kilimchoi** [comment]
I believe that http://www.slicedham.co is a better place for highlighting an individual entry.

**Comment by mike-u** [comment]
Alright, thanks.

**Pull request closed without merging**
