### PR TITLE
Adding Skcript's blog

### PR DESCRIPTION
**Pull request by imkarthikk**
Have added Skcript's blog. http://blog.skcript.com/

### CODE REVIEW

**Comment by kilimchoi** [comment]
please run opml generator.

**Comment by imkarthikk** [comment]
Oops. Sorry. Running that now.

**Comment by imkarthikk** [comment]
@kilimchoi : Done. :)

**Comment by kilimchoi** [comment]
@duckspeaker we shouldn't have merged this... I don't see too many interesting content.

**Comment by duckspeaker** [comment]
Sorry I thought you had [implicitly] approved it by commenting but not saying there wasn't enough tech content. I'll remove it.

**Comment by kilimchoi** [comment]
Sorry, I was checking that PR very late at night haha and I didn't get to check out the blog. I only saw that he was missing a link in the opml file. I will be more explicit next time.

**Comment by imkarthikk** [comment]
Sad to know that it has been rejected. Will take this as an opportunity to improvise on my company's blog. Thanks guys.

**Pull request merged**
